# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tWDrOTz-oObcK6K_fkYv_4s1RR1NFmxv
"""

import matplotlib.pyplot as plt

# Dados do relatório para o período de 2002 a 2019
anos = list(range(2002, 2020))
acidentes_totais = [19647, 21541, 22841, 24173, 23702, 24663, 25027, 25903, 23758, 23534,
                    27492, 20309, 14694, 14525, 14058, 13419, 13480, 12538]
acidentes_feridos = [9933, 9910, 9961, 10768, 11593, 12105, 10979, 9637, 8704, 7961,
                     10058, 14873, 12907, 10931, 12207, 11338, 10989, 10278]
acidentes_fatais = [360, 317, 318, 355, 325, 327, 332, 305, 351, 367, 357, 350, 372, 305,
                    274, 219, 191, 198]

# Criação do gráfico
plt.figure(figsize=(14, 8))

# Plotando os dados
plt.plot(anos, acidentes_totais, label="Acidentes Totais", color="royalblue", marker="o", linestyle="-")
plt.plot(anos, acidentes_feridos, label="Acidentes com Vítimas Feridas", color="green", marker="o", linestyle="--")
plt.plot(anos, acidentes_fatais, label="Acidentes Fatais", color="red", marker="o", linestyle=":")

# Adicionando os valores dos pontos
for i, ano in enumerate(anos):
    plt.text(ano, acidentes_totais[i] + 500, str(acidentes_totais[i]), ha='center', fontsize=9, color="royalblue")
    plt.text(ano, acidentes_feridos[i] + 500, str(acidentes_feridos[i]), ha='center', fontsize=9, color="green")
    plt.text(ano, acidentes_fatais[i] + 300, str(acidentes_fatais[i]), ha='center', fontsize=9, color="red")

# Anotações de eventos importantes
plt.annotate('Criação do projeto Visão Zero', xy=(2014, 14525), xytext=(2014, 18000),
             arrowprops=dict(facecolor='black', shrink=0.05), fontsize=10, color="black")
plt.annotate('Início das ciclofaixas e maior fiscalização', xy=(2015, 14058), xytext=(2015, 16000),
             arrowprops=dict(facecolor='black', shrink=0.05), fontsize=10, color="black")

# Título e rótulos dos eixos
plt.title("Evolução dos Acidentes de Trânsito em Fortaleza (2002-2019)", fontsize=16)
plt.xlabel("Ano", fontsize=14)
plt.ylabel("Número de Acidentes", fontsize=14)

# Configurações de legenda e grid
plt.legend(loc="upper right", fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)

# Limites dos eixos
plt.ylim(0, max(acidentes_totais) + 5000)
plt.xlim(min(anos), max(anos))

# Exibe o gráfico
plt.tight_layout()
plt.show()